name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: in path
        run: cd ./TimerMessageFrame/Bin/
      - name: make
        run: make
      - name: run test
        run: ./TMService
