name: TMServiceCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: make file
        run: |
          cd ./TimerMessageFrame/Bin/;
          ls;
          make;
          ./TMService;
